[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
sign_document_contract = "Su7vAnaGnHb7KFZJjKDKm1uhVmAgn47hJDWV4VivhXt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./my-wallet/my-deploy-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
